/*
 * App Stopwatch API
 *
 * API to access and configure the app stopwatch
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apiserver

import (
	"context"
	"net/http"
)

// UtilsApiRouter defines the required methods for binding the api requests to a responses for the UtilsApi
// The UtilsApiRouter implementation should parse necessary information from the http request,
// pass the data to a UtilsApiServicer to perform the required actions, then write the service results to the http response.
type UtilsApiRouter interface {
	GetStatus(http.ResponseWriter, *http.Request)
}

// UtilsApiServicer defines the api actions for the UtilsApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type UtilsApiServicer interface {
	GetStatus(context.Context) (ImplResponse, error)
}
