/*
 * App Stopwatch API
 *
 * API to access and configure the app stopwatch
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apiservices

import (
	"context"
	"net/http"
	"stopwatch/apiserver"
)

// UtilsApiService is a service that implements the logic for the UtilsApiServicer
// This service should implement the business logic for every endpoint for the UtilsApi API.
// Include any external packages or services that will be required by this service.
type UtilsApiService struct {
}

// NewUtilsApiService creates a default api service
func NewUtilsApiService() apiserver.UtilsApiServicer {
	return &UtilsApiService{}
}

// GetStatus - Get the status of the app
func (s *UtilsApiService) GetStatus(ctx context.Context) (apiserver.ImplResponse, error) {
	resp := apiserver.Status{
		Up: true,
	}

	return apiserver.Response(http.StatusOK, resp), nil
}
